### PR TITLE
Make sure input text color actually is black

### PR DESCRIPTION
**Pull request by hello-smile6**
Resolves https://github.com/webdev03/scratchinfo/pull/53#issuecomment-1031042365
#53

### CODE REVIEW

**Comment by webdev03** [comment]
Hmm... @hello-smile6 there's already a tailwind class `text-black` and 
image
works

**Comment by hello-smile6** [comment]
> Hmm... @hello-smile6 there's already a tailwind class `text-black` and image works

Wrong file, then

**Comment by hello-smile6** [comment]
Found it!

**Comment by hello-smile6** [comment]
Could you add pnpm to your dependencies?

**Comment by hello-smile6** [comment]
Fixed it!

**Comment by webdev03** [comment]
Thank you!

**Comment by hello-smile6** [comment]
> Thank you!

Told you I'd found a UI bug! Could you tell vercel to do deployments for my PRs?

**Comment by hello-smile6** [comment]
It worked! (I'd use `Capture node screenshot`, but the Photos app crashes since I have no disk space)
image

**Comment by webdev03** [comment]
> > Thank you!
> 
> Told you I'd found a UI bug! Could you tell vercel to do deployments for my PRs?

Well it's for security of my environment variables. Sorry!

**Comment by hello-smile6** [comment]
> > > Thank you!
> > 
> > 
> > Told you I'd found a UI bug! Could you tell vercel to do deployments for my PRs?
> 
> Well it's for security of my environment variables. Sorry!

Oh. :( Why do you even have environment variables? How do you do anything with private information? Someone really needs to set up a mirror of the Scratch cloud logs, so people can read variables without getting signed out. Could you, by chance?

**Comment by webdev03** [comment]
I have environment variables for my keys and URLs for database access and also signing keys.

**Comment by hello-smile6** [comment]
> I have environment variables for my keys and URLs for database access and also signing keys.

Oh. Could you make it somehow not have those?

**Comment by hello-smile6** [comment]
Would the `-pipe` option of gcc make compiling things on v86 faster?

**Comment by webdev03** [comment]
> > I have environment variables for my keys and URLs for database access and also signing keys.
> 
> Oh. Could you make it somehow not have those?

Impossible.

**Comment by hello-smile6** [comment]
> > > I have environment variables for my keys and URLs for database access and also signing keys.
> > 
> > 
> > Oh. Could you make it somehow not have those?
> 
> Impossible.

Oh.

**Pull request merged**
