### PR TITLE
Fix my website link when clicking my username/icon

### PR DESCRIPTION
**Pull request by JoshAtticus**
For all-contributors on readme.md

### CODE REVIEW

**Comment by hello-smile6** [comment]
What?

**Comment by webdev03** [comment]
This PR was the start of me changing all my passwords 🤣
I did it myself anyways to update the README

**Comment by JoshAtticus** [comment]
> What?

joshatticus.tk no longer exists

**Comment by JoshAtticus** [comment]
> This PR was the start of me changing all my passwords 🤣 (@Chiroyce1 would know) I did it myself anyways to update the README

Wdym?

**Comment by webdev03** [comment]
I accidentally ran `npx all-contributors generate` (to generate the readme) instead of `npx all-contributors-cli generate` and thought I had accidentally ran a malicious NPM package.

**Comment by JoshAtticus** [comment]
> I accidentally ran `npx all-contributors generate` (to generate the readme) instead of `npx all-contributors-cli generate` and thought I had accidentally ran a malicious NPM package.

Oh lol 🤣

**Pull request closed without merging**
