### PR TITLE
Add isScratcher value to API

### PR DESCRIPTION
**Pull request by hello-smile6**
Uses my brand-new API! (It's so new, it doesn't even have a homepage yet... But it will once I set up `express.static()`!

### CODE REVIEW

**Comment by webdev03** [comment]
Honestly I'd rather keep the logic for this on my vercel deployment - it would make things much faster.

**Comment by hello-smile6** [comment]
> Honestly I'd rather keep the logic for this on my vercel deployment - it would make things much faster.

Where is that? I couldn't find the user validation code.

**Comment by webdev03** [comment]
> > 
> 
> Where is that? I couldn't find the user validation code.

https://github.com/webdev03/scratchinfo/blob/main/src/lib/getStatus.ts

**Comment by hello-smile6** [comment]
> Honestly I'd rather keep the logic for this on my vercel deployment - it would make things much faster. Maybe I should try `node-html-parser` and see how that goes again.

You can use my code. https://github.com/hello-smile6/isScratcher

**Comment by webdev03** [comment]
I actually made one earlier.. but building game some "`canvas`" error

**Comment by hello-smile6** [comment]
So, where is your authentication script? I couldn't find it.

**Comment by webdev03** [comment]
Authentication is managed https://github.com/webdev03/scratchinfo/tree/main/src/routes/you/supa/scratchlight

**Comment by hello-smile6** [comment]
#53

**Pull request closed without merging**
